set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/sync_fifo_posedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/sync_fifo_posedge_const.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/sync_fifo_negedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/sync_fifo_negedge_const.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/async_fifo_posedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/async_fifo_posedge_const.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/async_fifo_negedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/async_fifo_negedge_const.xdc id:4} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold  0.02 [get_clocks clk]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 2.0 [get_ports {rst wr_en rd_en data_in[*]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.0 [get_ports {rst wr_en rd_en data_in[*]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -max 2.0 [get_ports {data_out[*] full empty}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -min 0.0 [get_ports {data_out[*] full empty}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports rst]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_ports rst]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_fix_hold [get_clocks clk]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 25.000 -name clk -waveform {0.000 10.000} [get_ports clk]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold  0.02 [get_clocks clk]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 2.0 [get_ports {rst wr_en rd_en data_in[*]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.0 [get_ports {rst wr_en rd_en data_in[*]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -max 2.0 [get_ports {data_out[*] full empty}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -min 0.0 [get_ports {data_out[*] full empty}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports rst]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_ports rst]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_fix_hold [get_clocks clk]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks wclk]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.100 [get_clocks wclk]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.200 [get_clocks rclk]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.100 [get_clocks rclk]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports wrst_n]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports rrst_n]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports {rdata[*]}]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports full]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports empty]
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks wclk]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.100 [get_clocks wclk]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks rclk]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.100 [get_clocks rclk]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports wrst_n]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports rrst_n]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports {rdata[*]}]
set_property src_info {type:XDC file:4 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports full]
set_property src_info {type:XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports empty]
