set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/sync_fifo_posedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/sync_fifo_posedge_const.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/sync_fifo_negedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/sync_fifo_negedge_const.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/async_fifo_posedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/async_fifo_posedge_const.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/async_fifo_negedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/async_fifo_negedge_const.xdc id:4} [current_design]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold  0.02 [get_clocks clk]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_ports rst]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_fix_hold [get_clocks clk]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold  0.02 [get_clocks clk]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_ports rst]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_fix_hold [get_clocks clk]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 30.000 -name wclk -waveform {0.000 15.000} [get_ports wclk]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 40.000 -name rclk -waveform {0.000 20.000} [get_ports rclk]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks wclk]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.150 [get_clocks wclk]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks rclk]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.150 [get_clocks rclk]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks wclk] -group [get_clocks rclk]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock wclk -max 4.000 [get_ports {wrst_n wr_en}]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock wclk -min 2.000 [get_ports {wrst_n wr_en}]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock wclk -max 4.000 [get_ports {wdata[*]}]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock wclk -min 2.000 [get_ports {wdata[*]}]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock rclk -max 5.000 [get_ports {rrst_n rd_en}]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock rclk -min 2.000 [get_ports {rrst_n rd_en}]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock wclk -max 5.000 [get_ports full]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock wclk -min 2.000 [get_ports full]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock rclk -max 5.000 [get_ports {rdata[*]}]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock rclk -min 2.000 [get_ports {rdata[*]}]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock rclk -max 5.000 [get_ports empty]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock rclk -min 2.000 [get_ports empty]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks wclk] -to [get_clocks rclk]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks rclk] -to [get_clocks wclk]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports wrst_n]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports rrst_n]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 5.0 [get_ports {rdata[*]}]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 5.0 [get_ports full]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 5.0 [get_ports empty]
set_property src_info {type:XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 30.000 -name wclk -waveform {0.000 15.000} [get_ports wclk]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 40.000 -name rclk -waveform {0.000 20.000} [get_ports rclk]
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks wclk]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.100 [get_clocks wclk]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.300 [get_clocks rclk]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold 0.100 [get_clocks rclk]
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks wclk] -group [get_clocks rclk]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock wclk -max 3.500 [get_ports {wrst_n wr_en}]
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock wclk -min 2.000 [get_ports {wrst_n wr_en}]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock wclk -max 3.500 [get_ports {wdata[*]}]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock wclk -min 2.000 [get_ports {wdata[*]}]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock rclk -max 3.000 [get_ports {rrst_n rd_en}]
set_property src_info {type:XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock rclk -min 2.000 [get_ports {rrst_n rd_en}]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock wclk -max 4.000 [get_ports full]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock wclk -min 2.000 [get_ports full]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock rclk -max 4.000 [get_ports {rdata[*]}]
set_property src_info {type:XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock rclk -min 2.000 [get_ports {rdata[*]}]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock rclk -max 4.000 [get_ports empty]
set_property src_info {type:XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock rclk -min 2.000 [get_ports empty]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks wclk] -to [get_clocks rclk]
set_property src_info {type:XDC file:4 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks rclk] -to [get_clocks wclk]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports wrst_n]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports rrst_n]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports {rdata[*]}]
set_property src_info {type:XDC file:4 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports full]
set_property src_info {type:XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_load -max 3.0 [get_ports empty]
