set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/sync_fifo_posedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/sync_fifo_posedge_const.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/RTL_Design/FIFO/FIFO.srcs/constrs_1/new/sync_fifo_negedge_const.xdc rfile:../../../FIFO.srcs/constrs_1/new/sync_fifo_negedge_const.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold  0.02 [get_clocks clk]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_ports rst]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_fix_hold [get_clocks clk]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_clock_uncertainty -hold  0.02 [get_clocks clk]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to   [get_ports rst]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_fix_hold [get_clocks clk]
